[tool.poetry]
name = "blockchainlab"
version = "0.1.0"
description = ""
authors = ["madgeniusblink <madgeniusblink@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
web3 = "^6.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
